# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 7, 1, 18, 51, 52, 893591, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
